### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by 546h8** [546h8/chat-app#8]
#IPアドレス
18.182.77.248

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

### [修正箇所]
①Editの文字色をカリキュラムの指定の色にしましょう
②サイドバーとチャットメッセージ一覧の境目の余白もカリキュラムの指定の色にしましょう
③グループを作成して１回目のメッセージ送信で自動更新ができるようにしましょう

### [修正箇所の現在の画像]
①、②
![スクリーンショット 2020-06-24 16 49 13](https://user-images.githubusercontent.com/49669977/85518124-e6842600-b63a-11ea-8267-37ea716efbe9.png)


③
<img width="1431" alt="自動更新" src="https://user-images.githubusercontent.com/49669977/85518175-ef74f780-b63a-11ea-9f7b-8f2a7aa88b60.png">


### [修正箇所の見本画像（カリキュラム内の画像）]
①
![スクリーンショット 2020-06-24 16 52 55](https://user-images.githubusercontent.com/49669977/85518416-2c40ee80-b63b-11ea-80e1-0448271fed0e.png)


②
![スクリーンショット 2020-06-24 16 53 15](https://user-images.githubusercontent.com/49669977/85518464-38c54700-b63b-11ea-94fc-bea9fc9e55e3.png)


修正が完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by 546h8** [comment]
該当箇所修正しました。

**Comment by yasunamiura** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
※今後実装に関する質問がありましたら、メンターに確認をお願いします！
